import { handleAdminCars } from "./cms.js";
import { issueAdminToken, verifyAdminToken } from "./admin-auth.js";
import { verifyAdminPassword, setAdminPassword, verifyAdminRecoveryCode, rotateAdminRecoveryCode } from "./admin-password.js";
import { storeMedia } from "./media.js";

const SEC={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"camera=(), microphone=(), geolocation=()","Cross-Origin-Resource-Policy":"same-origin","Strict-Transport-Security":"max-age=31536000; includeSubDomains; preload"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...SEC,...headers}});
const text=(v,n)=>String(v??"").trim().slice(0,n); const num=v=>Number.isFinite(Number(v))?Number(v):0;
const LEAD_STATUSES=new Set(["new","contacted","qualified","won","lost"]);
const MEDIA_KEY_RE=/^(?:admin|vehicles)\/[A-Za-z0-9._-]+(?:\/[A-Za-z0-9._-]+)*$/;
const MEDIA_UPLOAD_MAX_BYTES=5*1024*1024;
async function adminLogin(request,env){const body=await request.json().catch(()=>({}));const password=String(body.password||"").trim();if(!env.ADMIN_PASSWORD)return json({error:"Admin credentials chưa được cấu hình"},503);let valid=await verifyAdminPassword(env,password);if(!valid&&password===String(env.ADMIN_PASSWORD))valid=true;if(!valid)return json({error:"Sai mật khẩu"},401);const token=await issueAdminToken(env);if(!token)return json({error:"Không thể tạo phiên Admin"},503);return json({ok:true,token});}
async function adminForgotPassword(request,env){const body=await request.json().catch(()=>({}));const recoveryCode=String(body.recoveryCode||"").trim();const password=String(body.password||"");const confirm=String(body.confirm||"");if(!env.ADMIN_TOKEN)return json({error:"Recovery credentials chưa được cấu hình"},503);if(!(await verifyAdminRecoveryCode(env,recoveryCode)))return json({error:"Mã khôi phục không hợp lệ"},401);if(password.length<8)return json({error:"Mật khẩu mới phải có ít nhất 8 ký tự"},400);if(password!==confirm)return json({error:"Xác nhận mật khẩu không khớp"},400);if(!env.DB)return json({error:"D1 chưa kết nối"},503);await setAdminPassword(env,password);return json({ok:true,message:"Đã đặt mật khẩu Admin mới. Bạn có thể đăng nhập bằng mật khẩu mới."});}
async function adminRotateRecovery(request,env){const body=await request.json().catch(()=>({}));const rotateToken=String(body.rotateToken||"").trim();const authenticated=await requireAuth(request,env);const bootstrap=Boolean(env.ADMIN_RECOVERY_ROTATE_TOKEN&&rotateToken&&rotateToken===String(env.ADMIN_RECOVERY_ROTATE_TOKEN));if(!authenticated&&!bootstrap)return json({error:"Unauthorized"},401,{"WWW-Authenticate":"Bearer"});const code=await rotateAdminRecoveryCode(env);return json({ok:true,recoveryCode:code,message:"Mã khôi phục mới chỉ được hiển thị một lần. Không lưu vào log hoặc gửi qua chat."});}
const deny=()=>json({error:"Unauthorized"},401,{"WWW-Authenticate":"Bearer"});
async function requireAuth(request,env){return (await verifyAdminToken(request,env)).ok;}
async function requireMediaAuth(request,env){if(await requireAuth(request,env))return true;const supplied=String(request.headers.get("X-Admin-Token")||"");return !!env.ADMIN_TOKEN&&supplied!==""&&supplied===String(env.ADMIN_TOKEN);}
async function handleMediaUpload(request,env){if(request.method!=="POST")return json({error:"Method Not Allowed"},405,{Allow:"POST"});if(!env.MEDIA)return json({error:"MEDIA chưa được kết nối"},503);const contentType=String(request.headers.get("content-type")||"application/octet-stream").split(";",1)[0].trim().toLowerCase();if(!/^(?:image\/(?:jpeg|png|webp)|application\/pdf)$/.test(contentType))return json({error:"Unsupported media type"},415);const length=Number(request.headers.get("content-length")||0);if(length>MEDIA_UPLOAD_MAX_BYTES)return json({error:"Media quá lớn"},413);const body=await request.arrayBuffer();if(!body.byteLength)return json({error:"Media rỗng"},400);if(body.byteLength>MEDIA_UPLOAD_MAX_BYTES)return json({error:"Media quá lớn"},413);const ext=contentType==="image/jpeg"?"jpg":contentType==="image/png"?"png":contentType==="image/webp"?"webp":"pdf";const key=`admin/${Date.now()}-${crypto.randomUUID()}.${ext}`;await storeMedia(env,key,body,contentType);return json({ok:true,key,url:`/media/${encodeURIComponent(key)}`,contentType,bytes:body.byteLength});}
async function handleMediaDelete(request,env,u){if(request.method!=="DELETE")return json({error:"Method Not Allowed"},405,{Allow:"DELETE"});if(!env.MEDIA)return json({error:"MEDIA chưa được kết nối"},503);let key;try{key=decodeURIComponent(u.pathname.slice("/api/admin/media/".length));}catch{return json({error:"Media key không hợp lệ"},400);}if(!key||key.length>1024||key.includes("..")||!MEDIA_KEY_RE.test(key))return json({error:"Media key không hợp lệ"},400);await env.MEDIA.delete(key);return json({ok:true,key,deleted:true});}
async function handleLeads(request,env,u){if(request.method!=="GET"&&request.method!=="PUT"&&request.method!=="DELETE")return json({error:"Method Not Allowed"},405);if(!env.DB)return json({error:"D1 chưa được kết nối"},503);if(request.method==="GET"){const q=text(u.searchParams.get("q"),120),status=text(u.searchParams.get("status"),30);let sql="SELECT id,name,phone,car_id,message,status,note,created_at,updated_at FROM leads",args=[],where=[];if(q){where.push("(name LIKE ? OR phone LIKE ? OR car_id LIKE ? OR message LIKE ? OR note LIKE ?)");const x=`%${q}%`;args.push(x,x,x,x,x)}if(status&&LEAD_STATUSES.has(status)){where.push("status=?");args.push(status)}if(where.length)sql+=" WHERE "+where.join(" AND ");sql+=" ORDER BY created_at DESC LIMIT 500";const result=await env.DB.prepare(sql).bind(...args).all();return json({leads:result.results||[],count:(result.results||[]).length});}const raw=await request.json().catch(()=>null),id=num(raw?.id);if(!id)return json({error:"ID không hợp lệ"},400);if(request.method==="PUT"){const status=text(raw.status||"new",30),note=text(raw.note,3000);if(!LEAD_STATUSES.has(status))return json({error:"Trạng thái lead không hợp lệ"},400);await env.DB.prepare("UPDATE leads SET status=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,note,id).run();return json({ok:true});}await env.DB.prepare("DELETE FROM leads WHERE id=?").bind(id).run();return json({ok:true,deleted:true});}
export async function handleAppAdmin(request,env){const u=new URL(request.url);if(request.method==="POST"&&u.pathname==="/api/admin/login")return adminLogin(request,env);if(request.method==="POST"&&u.pathname==="/api/admin/forgot-password")return adminForgotPassword(request,env);if(request.method==="POST"&&u.pathname==="/api/admin/recovery/rotate")return adminRotateRecovery(request,env);if(u.pathname==="/api/admin/media"||u.pathname.startsWith("/api/admin/media/")){if(!(await requireMediaAuth(request,env)))return deny();if(u.pathname==="/api/admin/media")return handleMediaUpload(request,env);return handleMediaDelete(request,env,u);}if(!u.pathname.startsWith("/api/admin/"))return null;if(!(await requireAuth(request,env)))return deny();if(u.pathname.startsWith("/api/admin/cars")){if(request.method==="DELETE"){const headers=new Headers(request.headers);headers.set("X-CMS-Confirm","delete");request=new Request(request,{headers});}return handleAdminCars(request,env);}if(u.pathname==="/api/admin/leads")return handleLeads(request,env,u);if(u.pathname==="/api/admin/dashboard"){if(request.method!=="GET")return json({error:"Method Not Allowed"},405);if(!env.DB)return json({error:"D1 missing"},503);const [carsN,leadsN,soldN,reservedN,newLeadsN]=await Promise.all([env.DB.prepare("SELECT COUNT(*) n FROM cars").first("n"),env.DB.prepare("SELECT COUNT(*) n FROM leads").first("n"),env.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='sold'").first("n"),env.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='reserved'").first("n"),env.DB.prepare("SELECT COUNT(*) n FROM leads WHERE status='new'").first("n")]);return json({stats:{cars:Number(carsN||0),leads:Number(leadsN||0),sold:Number(soldN||0),reserved:Number(reservedN||0),newLeads:Number(newLeadsN||0)}});}return null;}
