import { analyzeVehicleImage } from "./vehicle-ai.js";

const SEC={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Strict-Transport-Security":"max-age=31536000; includeSubDomains; preload"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...SEC,...headers}});
const text=(v,n)=>String(v??"").trim().slice(0,n); const num=v=>Number.isFinite(Number(v))?Number(v):0;
const STATUSES=new Set(["available","reserved","sold"]);
const auth=(r,e)=>{const t=e.APP_API_TOKEN,a=r.headers.get("Authorization")||"";return !!t&&a.startsWith("Bearer ")&&a.slice(7)===t};
const deny=()=>json({error:"Unauthorized"},401,{"WWW-Authenticate":"Bearer"}); async function body(r){return r.json().catch(()=>null)}
async function images(db,carId){const q=await db.prepare("SELECT id,url,sort_order,is_cover FROM car_images WHERE car_id=? ORDER BY sort_order,id").bind(carId).all();return q.results||[]}
function norm(c,imgs=[]){let features=[];try{features=JSON.parse(c.features_json||"[]")}catch{}return {...c,features,images:imgs,cover_image:c.cover_image||imgs.find(x=>x.is_cover)?.url||imgs[0]?.url||""}}
function valid(b){if(!b||!/^[a-z0-9][a-z0-9-_]{2,80}$/i.test(String(b.id||"")))return"ID bài đăng không hợp lệ";if(!text(b.brand,100)||!text(b.model,160))return"Hãng và mẫu xe là bắt buộc";if(b.status!=null&&!STATUSES.has(text(b.status,30)))return"Trạng thái xe không hợp lệ";return null}
async function saveImages(db,carId,items){if(!Array.isArray(items))return;await db.prepare("DELETE FROM car_images WHERE car_id=?").bind(carId).run();const rows=items.slice(0,30);if(rows.length)await db.batch(rows.map((x,i)=>db.prepare("INSERT INTO car_images (car_id,url,sort_order,is_cover) VALUES (?,?,?,?)").bind(carId,text(typeof x==='string'?x:x?.url,200000),i,i===0?1:((typeof x==='object'&&x?.is_cover)?1:0))))}
async function cars(r,e,carId){if(!e.DB)return json({error:"D1 chưa được kết nối"},503);if(carId){const c=await e.DB.prepare("SELECT * FROM cars WHERE id=?").bind(carId).first();if(!c)return json({error:"Không tìm thấy xe"},404);if(r.method==='GET')return json({car:norm(c,await images(e.DB,carId))});if(r.method==='DELETE'){await e.DB.prepare("DELETE FROM car_images WHERE car_id=?").bind(carId).run();const result=await e.DB.prepare("DELETE FROM cars WHERE id=?").bind(carId).run();if(Number(result?.meta?.changes||0)!==1)return json({error:"Không tìm thấy xe"},404);return json({ok:true,id:carId,deleted:true});}if(r.method!=='PUT')return json({error:"Method Not Allowed"},405,{Allow:"GET,PUT,DELETE"});const b=await body(r),merged={...c,...b,id:carId};const er=valid(merged);if(er)return json({error:er},400);const v=[text(merged.brand,100),text(merged.model,160),num(merged.year)||null,num(merged.mileage),num(merged.price),text(merged.fuel,100),text(merged.category||'suv',40),text(merged.color,80),text(merged.status||'available',30),text(merged.description,10000),JSON.stringify(Array.isArray(merged.features)?merged.features.slice(0,80):[]),merged.featured?1:0,text(merged.cover_image,200000),carId];await e.DB.prepare("UPDATE cars SET brand=?,model=?,year=?,mileage=?,price=?,fuel=?,category=?,color=?,status=?,description=?,features_json=?,featured=?,cover_image=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(...v).run();if(Array.isArray(b.images))await saveImages(e.DB,carId,b.images);return json({ok:true,id:carId});}
if(r.method==='GET'){const u=new URL(r.url),q=text(u.searchParams.get('q'),120),status=text(u.searchParams.get('status'),30);if(status&&!STATUSES.has(status))return json({error:"Trạng thái xe không hợp lệ"},400);let sql="SELECT * FROM cars",args=[];const where=[];if(q){where.push("(id LIKE ? OR brand LIKE ? OR model LIKE ?)");const x=`%${q}%`;args.push(x,x,x)}if(status){where.push("status=?");args.push(status)}if(where.length)sql+=` WHERE ${where.join(' AND ')}`;sql+=" ORDER BY featured DESC,created_at DESC LIMIT 500";const rs=await e.DB.prepare(sql).bind(...args).all();return json({cars:await Promise.all((rs.results||[]).map(async c=>norm(c,await images(e.DB,c.id))))})}
if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"GET,POST"});const b=await body(r),er=valid(b);if(er)return json({error:er},400);const newId=text(b.id,81),v=[newId,text(b.brand,100),text(b.model,160),num(b.year)||null,num(b.mileage),num(b.price),text(b.fuel,100),text(b.category||'suv',40),text(b.color,80),text(b.status||'available',30),text(b.description,10000),JSON.stringify(Array.isArray(b.features)?b.features.slice(0,80):[]),b.featured?1:0,text(b.cover_image,200000)];try{await e.DB.prepare("INSERT INTO cars (id,brand,model,year,mileage,price,fuel,category,color,status,description,features_json,featured,cover_image) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(...v).run()}catch(x){return json({error:String(x.message||x).includes('UNIQUE')?'ID bài đăng đã tồn tại':String(x.message||x)},409)}if(Array.isArray(b.images))await saveImages(e.DB,newId,b.images);return json({ok:true,id:newId},201)}
async function upload(r,e){if(!e.MEDIA)return json({error:"MEDIA chưa được kết nối"},503);if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"POST"});const type=r.headers.get("content-type")||"application/octet-stream";if(!type.startsWith("image/"))return json({error:"Chỉ nhận image/*"},415);const len=Number(r.headers.get("content-length")||0);if(len>12*1024*1024)return json({error:"Ảnh vượt quá 12MB"},413);const bytes=await r.arrayBuffer();if(bytes.byteLength>12*1024*1024)return json({error:"Ảnh vượt quá 12MB"},413);const ext=(type.split('/')[1]||'jpeg').replace(/[^a-z0-9]/gi,'').slice(0,10)||'jpeg';const mediaId=crypto.randomUUID(),key=`app/${new Date().toISOString().slice(0,10)}/${mediaId}.${ext}`;await e.MEDIA.put(key,bytes,{httpMetadata:{contentType:type,cacheControl:"public,max-age=31536000,immutable"}});return json({ok:true,key,url:`/media/${encodeURIComponent(key)}`},201)}
async function analyze(r,e){if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"POST"});const type=r.headers.get("content-type")||"image/jpeg";if(!type.startsWith("image/"))return json({error:"Chỉ nhận image/*"},415);const bytes=await r.arrayBuffer();if(bytes.byteLength>12*1024*1024)return json({error:"Ảnh vượt quá 12MB"},413);const caption=text(new URL(r.url).searchParams.get('caption'),2000);try{return json({ok:true,analysis:await analyzeVehicleImage(e,bytes,type,caption)})}catch(x){console.error("app_vehicle_analyze",String(x?.message||x));return json({error:"Vehicle AI không khả dụng"},503)}}
function decodeCarId(pathname){const raw=pathname.slice('/api/app/v1/cars/'.length);try{return decodeURIComponent(raw)}catch{return null}}
export async function handleAppApi(r,e){const u=new URL(r.url);if(!u.pathname.startsWith('/api/app/v1/'))return null;if(u.pathname==='/api/app/v1/health')return json({ok:true,service:'app-api',version:'1.0.0',timestamp:new Date().toISOString()});if(!auth(r,e))return deny();if(!e.DB&&/^\/api\/app\/v1\/cars/.test(u.pathname))return json({error:"D1 chưa được kết nối"},503);if(u.pathname==='/api/app/v1/cars')return cars(r,e);if(u.pathname.startsWith('/api/app/v1/cars/')){const carId=decodeCarId(u.pathname);if(carId===null)return json({error:"ID xe không hợp lệ"},400);return cars(r,e,carId)}if(u.pathname==='/api/app/v1/media')return upload(r,e);if(u.pathname==='/api/app/v1/vehicle/analyze')return analyze(r,e);if(u.pathname==='/api/app/v1/dashboard'&&r.method==='GET'){const [carsN,leadsN,soldN,reservedN,newLeadsN]=await Promise.all([e.DB.prepare("SELECT COUNT(*) n FROM cars").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM leads").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='sold'").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='reserved'").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM leads WHERE status='new'").first('n')]);return json({stats:{cars:Number(carsN||0),leads:Number(leadsN||0),sold:Number(soldN||0),reserved:Number(reservedN||0),newLeads:Number(newLeadsN||0)}})}return json({error:"Not Found"},404)}