const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}});
const SEC={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Permissions-Policy":"camera=(), microphone=(), geolocation=()","Cross-Origin-Opener-Policy":"same-origin","Strict-Transport-Security":"max-age=31536000; includeSubDomains; preload"};
const secure=r=>{const o=new Response(r.body,r);for(const[k,v]of Object.entries(SEC))o.headers.set(k,v);return o};
const auth=(r,e)=>{const t=e.ADMIN_TOKEN,a=r.headers.get("Authorization")||"";return !!t&&a.startsWith("Bearer ")&&a.slice(7)===t};
const body=async r=>r.json().catch(()=>null);const text=(v,n)=>String(v??"").trim().slice(0,n);const num=v=>Number.isFinite(Number(v))?Number(v):0;
async function initDb(db) {
  // Database schema is managed exclusively through D1 migrations.
  // No runtime DDL or schema mutation is performed here.
}

async function getImages(db,carId){const q=await db.prepare("SELECT id,url,sort_order,is_cover FROM car_images WHERE car_id=? ORDER BY sort_order,id").bind(carId).all();return q.results||[]}
async function saveImages(db,carId,images){await db.prepare("DELETE FROM car_images WHERE car_id=?").bind(carId).run();if(!Array.isArray(images)||!images.length)return;const rows=images.slice(0,30).map((x,i)=>typeof x==='string'?{url:x,sort_order:i,is_cover:i===0}:x);await db.batch(rows.map((x,i)=>db.prepare("INSERT INTO car_images (car_id,url,sort_order,is_cover) VALUES (?,?,?,?)").bind(carId,text(x.url,200000),Number.isFinite(Number(x.sort_order))?Number(x.sort_order):i,x.is_cover?1:0)))}
function validCar(b){if(!b||!/^[a-z0-9][a-z0-9-_]{2,80}$/i.test(String(b.id||"")))return"ID bài đăng không hợp lệ";if(!text(b.brand,100)||!text(b.model,160))return"Hãng và mẫu xe là bắt buộc";return null}
async function adminCars(r,e){if(!auth(r,e))return json({error:"Unauthorized"},401,{...SEC,"WWW-Authenticate":"Bearer"});if(!e.DB)return json({error:"D1 chưa được kết nối"},503,SEC);await initDb(e.DB);if(r.method==='GET'){const q=await e.DB.prepare("SELECT * FROM cars ORDER BY featured DESC,created_at DESC").all();const cars=await Promise.all((q.results||[]).map(async c=>({...c,images:await getImages(e.DB,c.id)})));return json({cars},200,SEC)}const b=await body(r),er=validCar(b);if(er)return json({error:er},400,SEC);const id=text(b.id,81),v=[text(b.brand,100),text(b.model,160),num(b.year)||null,num(b.mileage),num(b.price),text(b.fuel,100),text(b.category||'suv',40),text(b.color,80),text(b.status||'available',30),text(b.description,10000),JSON.stringify(Array.isArray(b.features)?b.features.slice(0,80):[]),b.featured?1:0,text(b.cover_image,200000)];if(r.method==='POST'){try{await e.DB.prepare("INSERT INTO cars (id,brand,model,year,mileage,price,fuel,category,color,status,description,features_json,featured,cover_image) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,...v).run()}catch(x){return json({error:String(x.message||x).includes('UNIQUE')?'ID bài đăng đã tồn tại':String(x.message||x)},409,SEC)}}else if(r.method==='PUT'){await e.DB.prepare("UPDATE cars SET brand=?,model=?,year=?,mileage=?,price=?,fuel=?,category=?,color=?,status=?,description=?,features_json=?,featured=?,cover_image=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(...v,id).run()}else if(r.method==='DELETE'){await e.DB.batch([e.DB.prepare("DELETE FROM car_images WHERE car_id=?").bind(id),e.DB.prepare("DELETE FROM cars WHERE id=?").bind(id)]);return json({ok:true,id},200,SEC)}else return json({error:'Method Not Allowed'},405,{...SEC,Allow:'GET,POST,PUT,DELETE'});await saveImages(e.DB,id,b.images||[]);return json({ok:true,id},r.method==='POST'?201:200,SEC)}
async function adminLeads(r,e){if(!auth(r,e))return json({error:'Unauthorized'},401,SEC);if(!e.DB)return json({error:'D1 chưa được kết nối'},503,SEC);await initDb(e.DB);if(r.method==='GET'){const q=await e.DB.prepare("SELECT * FROM leads ORDER BY created_at DESC LIMIT 500").all();return json({leads:q.results||[]},200,SEC)}const b=await body(r),id=num(b?.id);if(!id)return json({error:'ID lead không hợp lệ'},400,SEC);if(r.method==='PUT'){await e.DB.prepare("UPDATE leads SET status=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(text(b.status||'new',30),text(b.note,3000),id).run();return json({ok:true},200,SEC)}if(r.method==='DELETE'){await e.DB.prepare("DELETE FROM leads WHERE id=?").bind(id).run();return json({ok:true},200,SEC)}return json({error:'Method Not Allowed'},405,{...SEC,Allow:'GET,PUT,DELETE'})}
async function adminDashboard(r,e){if(!auth(r,e))return json({error:'Unauthorized'},401,SEC);if(!e.DB)return json({error:'D1 chưa được kết nối'},503,SEC);await initDb(e.DB);const [cars,leads,featured,sold,reserved,newLeads]=await Promise.all([e.DB.prepare("SELECT COUNT(*) n FROM cars").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM leads").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE featured=1").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='sold'").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='reserved'").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM leads WHERE status='new'").first('n')]);return json({stats:{cars:Number(cars||0),leads:Number(leads||0),featured:Number(featured||0),sold:Number(sold||0),reserved:Number(reserved||0),newLeads:Number(newLeads||0)}},200,SEC)}
async function staticCars(e,r){const x=await e.ASSETS.fetch(new Request(new URL('/data/cars.json',r.url)));if(!x.ok)throw Error('cars.json unavailable');return x.json()}
function norm(c,images=[]){let features=[];try{features=JSON.parse(c.features_json||'[]')}catch{}return{id:c.id,brand:c.brand||'',name:c.model||c.id||'Xe',category:c.category||'other',year:c.year==null?'':String(c.year),odo:c.mileage==null?'Liên hệ':`${Number(c.mileage).toLocaleString('vi-VN')} km`,seats:c.seats||'Liên hệ',engine:c.engine||c.fuel||'Liên hệ',drive:c.drive||'Liên hệ',price:c.price?`${Number(c.price).toLocaleString('vi-VN')} đ`:'Liên hệ',tag:c.status==='available'?'AVAILABLE':String(c.status||'').toUpperCase(),page:c.page||`car-${c.id}.html`,imageClass:c.imageClass||'',contact:'0866997891',color:c.color||'',description:c.description||'',images,features,featured:!!c.featured,cover_image:c.cover_image||images.find(x=>x.is_cover)?.url||images[0]?.url||''}}
export default{async fetch(r,e){const u=new URL(r.url);try{if(u.pathname==='/api/health')return json({ok:true,version:'V10 Admin CMS',timestamp:new Date().toISOString()},200,SEC);if(u.pathname==='/api/admin/cars')return adminCars(r,e);if(u.pathname==='/api/admin/leads')return adminLeads(r,e);if(u.pathname==='/api/admin/dashboard')return adminDashboard(r,e);if(u.pathname==='/api/cars'){if(r.method!=='GET')return json({error:'Method Not Allowed'},405,{...SEC,Allow:'GET'});if(e.DB){try{await initDb(e.DB);const q=await e.DB.prepare("SELECT * FROM cars ORDER BY featured DESC,created_at DESC").all();if(q.results?.length){const cars=await Promise.all(q.results.map(async c=>norm(c,await getImages(e.DB,c.id))));return json({source:'d1',cars},200,SEC)}}catch(x){console.error(x)}}return json({source:'static',cars:await staticCars(e,r)},200,SEC)}if(u.pathname==='/api/leads'){if(r.method!=='POST')return json({error:'Method Not Allowed'},405,{...SEC,Allow:'POST'});const b=await body(r),p=typeof b?.phone==='string'?b.phone.trim():'';if(p.replace(/\D/g,'').length<9)return json({error:'Số điện thoại không hợp lệ.'},400,SEC);if(!e.DB)return json({ok:true,stored:false},200,SEC);await initDb(e.DB);await e.DB.prepare("INSERT INTO leads (name,phone,car_id,message) VALUES (?,?,?,?)").bind(text(b.name,120),p,text(b.car_id,100),text(b.message,2000)).run();return json({ok:true,stored:true},200,SEC)}const x=secure(await e.ASSETS.fetch(r));if(/\.(css|js|png|jpg|jpeg|svg|webp|ico|woff|woff2)$/i.test(u.pathname))x.headers.set('Cache-Control','public,max-age=31536000,immutable');if(u.pathname==='/'||u.pathname.endsWith('.html'))x.headers.set('Cache-Control','no-cache');return x}catch(x){console.error(x);return json({ok:false,error:'Internal Server Error'},500,SEC)}}};